---
title: "Understanding Google Play Application Reviews"
author: "RTime2Shine"
date: "12/7/19"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-packages, message=FALSE}
library(tidyverse)
library(broom)
library(knitr) 
library(skimr)
library(readr)
library(ggplot2)
library(stringr)
library(lubridate)
library(Sleuth3) 
library(ISLR)
library(leaps)
```

```{r load-data, message=FALSE}
apps <- read_csv("/cloud/project/02-data/googleplaystore.csv")
apps$Price <- str_replace(apps$Price, "\\$", "")
apps$Size <- str_replace(apps$Size, "\\M", "")
apps$Installs <- str_replace(apps$Installs, "\\+", "")
apps$`Content Rating`<- str_replace(apps$`Content Rating`, "\\+", "")
apps$`Content Rating`<- str_replace(apps$`Content Rating`, "[[:digit:]]+", "")
levels(apps$`Content Rating`) <- c("Adults Only","Everyone","Mature", "Teen", "Unrated")
apps <- filter(apps, Reviews <= 203579)
apps$`Rating` <- as.numeric(apps$`Rating`)
apps <- apps %>% mutate(log_reviews = log(Reviews))
apps <- apps %>%
  na.omit(apps)
```



## Section 1: Introduction (includes introduction and exploratory data analysis)


Lukengu: relevel categories, log transform and remove the outliers of reviews



## Section 2: Regression Analysis (includes the final model and discussion of assumptions)
## Section 3: Discussion and Limitations 
## Section 4: Conclusion
## Section 5: Additional Work